### ISSUE TITLE
Deployment fails when mac address is 'none' in virt_platform.yml

### ISSUE THREAD

**Issue by joehakimrahme** [enovance/infra-virt#38]
Error:

```
libvirt: Domain Config error : XML error: unable to parse mac address 'none'
Traceback (most recent call last):
  File "/home/joe/infra-virt/virtualizor.py", line 594, in <module>
    main()
  File "/home/joe/infra-virt/virtualizor.py", line 570, in main
    hypervisor.conn.defineXML(host.dump_libvirt_xml())
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3484, in defineXML
    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirt.libvirtError: XML error: unable to parse mac address 'none'
```

**Comment by goneri** [comment]
The issue has been fixed by @ylamgarchal https://github.com/enovance/hardware/commit/b4b29273773a5a650760e90e37325b6878f26dc2
